# Generated by Django 4.1.7 on 2023-02-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estudiante_id',
        ),
    ]
