# Generated by Django 4.1.7 on 2023-02-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_alter_estudiante_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
    ]
