# Generated by Django 4.1.7 on 2023-02-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0006_alter_estudiante_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignatura',
            table='asignaturas',
        ),
        migrations.AlterModelTable(
            name='carrera',
            table='carreras',
        ),
        migrations.AlterModelTable(
            name='ciclo',
            table='ciclos',
        ),
        migrations.AlterModelTable(
            name='docente',
            table='docentes',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiantes',
        ),
        migrations.AlterModelTable(
            name='facultad',
            table='facultades',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matriculas',
        ),
        migrations.AlterModelTable(
            name='registroasistencia',
            table='registroAsistencias',
        ),
        migrations.AlterModelTable(
            name='universidad',
            table='universidades',
        ),
    ]
