# Generated by Django 4.1.7 on 2023-02-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0007_alter_asignatura_table_alter_carrera_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registroasistencia',
            table='registroasistencias',
        ),
    ]
